create sequence hibernate_sequence start 1 increment 1;

create table logger
(
    id             int4 generated by default as identity,
    action_details varchar(128) not null,
    action_type    varchar(128) not null,
    atomic         int2         not null,
    company_id     int4,
    created        timestamp    not null,
    table_name     varchar(128) not null,
    user_id        int4         not null,
    primary key (id)
);

create table role
(
    id   int4 generated by default as identity,
    name varchar(64) not null,
    primary key (id)
);

create table status
(
    id   int4 generated by default as identity,
    name varchar(64) not null,
    primary key (id)
);

create table usr
(
    id                   int4 generated by default as identity,
    company_id           int4,
    email                varchar(64) not null,
    first_name           varchar(64),
    last_name            varchar(64),
    location_id          int4,
    notification_type_id int4        not null,
    password             varchar(128),
    registration_date    timestamp   not null,
    role_id              int4        not null,
    status_id            int4        not null,
    token                varchar(64),
    username             varchar(64),
    primary key (id)
)